# **Data Cleaning**

In [33]:
import pandas as pd
import numpy as np
from pandas.api.types import is_numeric_dtype
from sklearn.preprocessing import LabelEncoder
from pandas.api.types import is_string_dtype

In [34]:
df=pd.read_csv("Data set before cleaning.csv")

### data set before Cleaning

In [35]:
df

,Name of the game,Fit platform,Num Of comments,Num Of likes,Raiting,Grade,Num of pros,Num of cons,First Released,The game rviewer,The date of the review
0,World Of Warcraft: Dragonflight Review In Prog...,PC,52,5,In Progress,9.0,5.0,4.0,"Nov 23, 2004",\n Cameron Koch\n,"December 7, 2022 at 11:45AM PST"
1,Crisis Core: Final Fantasy 7 Reunion Review - ...,PS5,45,10,Great,8.0,4.0,2.0,"Mar 24, 2008",\n Jessica Howard\n,"December 6, 2022 at 12:28PM PST"
2,The Callisto Protocol Review - I Don't Belong ...,XBSX,261,15,Mediocre,5.0,3.0,3.0,"Dec 2, 2022",\n Jordan Ramée\n,"December 1, 2022 at 9:00PM PST"
3,Marvel's Midnight Suns Review - XCOM Superhero...,PC,32,11,Great,8.0,3.0,2.0,"Dec 2, 2022",\n Jordan Ramée\n,"November 30, 2022 at 10:17AM PST"
4,Evil West Review - Undead Redemption,PC,32,9,Fair,6.0,3.0,3.0,"Nov 22, 2022",\n Richard Wakeling\n,"November 23, 2022 at 5:38PM PST"
...,...,...,...,...,...,...,...,...,...,...,...
4820,Air Conflicts: Aces of World War II Review,PSP,0,5,Fair,6.0,3.0,3.0,NaN,\n Kevin VanOrd\n,"April 29, 2009 at 8:10AM PDT"
4821,Cocoto Platform Jumper Review,WII,0,1,Poor,4.0,1.0,3.0,NaN,\n Chris Watters\n,"April 28, 2009 at 5:54PM PDT"
4822,Professor Heinz Wolff's Gravity Review,DS,0,0,Poor,4.5,1.0,3.0,NaN,\n Tom Mc Shea\n,"April 27, 2009 at 5:57PM PDT"
4823,Professor Heinz Wolff's Gravity Review,WII,0,0,Mediocre,5.0,1.0,2.0,NaN,\n Tom Mc Shea\n,"April 27, 2009 at 5:57PM PDT"
4824,Excitebots: Trick Racing Review,WII,0,0,Great,8.0,5.0,3.0,"Apr 20, 2009",\n Chris Watters\n,"April 24, 2009 at 7:56PM PDT"

In [36]:
df1=df.copy()

In [37]:
df1['The game rviewer'] = df1['The game rviewer'].str.replace('\n',"") #מחיקת תווים מיותרים משם מפרסם הסקירה

In [38]:
df1.drop_duplicates(inplace=True) #מחק כפילויות

In [39]:
# שינוי תאריך עליית הסקירה מתאריך מלא במלל לשנה
i=0
for date__ in df1['The date of the review']:
    new_date=date__
    v=0
    try:
        v=int(df1['The date of the review'][i].find(",", 0, 20))
    except:
        v=0
        
    if v!=0:
        v=v+2
        new_date=int(date__[v])*1000 + int(date__[v+1])*100 + int(date__[v+2])*10 + int(date__[v+3])
        df1['The date of the review'][i]=float(new_date)
    i+=1

In [40]:
# שינוי תאריך עליית המשחק מתאריך מלא במלל לשנה
i=0
for date_ in df1['First Released']:
    new_date=date_
    v=0
    try:
        v=int(df1['First Released'][i].find(",", 0, 20))  
    except:
        v=0
    if v != 0:
        try:
            new_date=int(date_[len(date_)-4])*1000 + int(date_[len(date_)-3])*100 + int(date_[len(date_)-2])*10 + int(date_[len(date_)-1])
            df1['First Released'][i]=float(new_date)
        except:
            df1['First Released'][i]=np.nan
    i+=1

In [41]:
#להפוך את הפלטפורה לכמות פלטפורמות שאפשר לשחק את המשחק
i=0
for fit_p in df1['Fit platform']:
    count=fit_p.count(',')
    df1['Fit platform'][i]=float(count+1)
    i+=1

In [42]:
#מספור השמות 
i=0
for name_ in df1['Name of the game']:
    df1['Name of the game'][i]=i
    i+=1

In [43]:
df1 = df1.dropna(subset=['Name of the game']) 
df1 = df1.drop(labels=['Raiting'],axis=1) #להעלים את עמודה Raiting

In [44]:
#מניעת תאריכים לא רצוים
w=0
for date_ in df1['First Released']:
    date1=float(df1['First Released'][w])
    if date1>2022:
        df1['First Released'][w]=np.nan
    w+=1

In [45]:
cols=df1[df1.columns[df1.columns!='Grade']]#outliers
for i in cols:
    if is_numeric_dtype(df1[i]):
        z_score=(df1[i]-df1[i].mean())/df1[i].std()
        outliers=(abs(z_score)>3)
        df1[i][outliers]=np.nan
        
    
df1 = df1.dropna()

In [46]:
dff=df1.copy()
for i in dff:
    if is_string_dtype(df1[i]):
        if type(df1[i][0])!=float: 
            dff[i]=LabelEncoder().fit_transform(dff[i])

### data set after Cleaning

In [47]:
dff

,Name of the game,Fit platform,Num Of comments,Num Of likes,Grade,Num of pros,Num of cons,First Released,The game rviewer,The date of the review
0,0,1.0,52.0,5.0,9.0,5.0,4.0,2004.0,19,2022.0
1,1,1.0,45.0,10.0,8.0,4.0,2.0,2008.0,73,2022.0
2,2,1.0,261.0,15.0,5.0,3.0,3.0,2022.0,77,2022.0
3,3,1.0,32.0,11.0,8.0,3.0,2.0,2022.0,77,2022.0
4,4,1.0,32.0,9.0,6.0,3.0,3.0,2022.0,117,2022.0
...,...,...,...,...,...,...,...,...,...,...
4810,2881,1.0,2.0,4.0,7.5,3.0,2.0,2009.0,130,2009.0
4811,2882,1.0,3.0,0.0,7.5,3.0,2.0,2009.0,130,2009.0
4817,2883,1.0,1.0,3.0,7.0,3.0,3.0,2009.0,115,2009.0
4818,2884,1.0,3.0,10.0,7.0,3.0,3.0,2009.0,115,2009.0
4824,2885,1.0,0.0,0.0,8.0,5.0,3.0,2009.0,27,2009.0

In [48]:
dff.to_csv('Data set after cleaning.csv',index = False)